config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :record_types
  root to: 'default#index'
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions"}
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'show'
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :record_type
  belongs_to :user

  validates :qt, :user, :record_type, presence: true
  validates_numericality_of :qt, greater_than: 0
end

app/models/record_type.rb
class RecordType < ApplicationRecord
  validates :name, :user, presence: true
  validates :name, length: { in: 2..30 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :last_name, presence: true
  validates :name, :last_name, length: { in: 2..50 }
  has_many :record_types, dependent: :destroy
  has_many :records, dependent: :destroy

  def full_name
    "#{name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index
  end
end

app/controllers/record_types_controller.rb
class RecordTypesController < ApplicationController
  before_action :set_record_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /record_types
  # GET /record_types.json
  def index
    @record_types = RecordType.where(user: current_user)
  end

  # GET /record_types/1
  # GET /record_types/1.json
  def show
  end

  # GET /record_types/new
  def new
    @record_type = RecordType.new
  end

  # GET /record_types/1/edit
  def edit
  end

  def create
    @record_type = RecordType.new(record_type_params)
    if @record_type.save
      redirect_to @record_type, notice: 'Record type was successfully created.'
    else
       render :new
    end
  end

  # PATCH/PUT /record_types/1
  def update
    if @record_type.update(record_type_params)
      redirect_to @record_type, notice: 'Record type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /record_types/1
  def destroy
    @record_type.destroy
    redirect_to record_types_url, notice: 'Record type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record_type
      @record_type = RecordType.find_by_id_and_user_id(params[:id], current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_type_params
      params.require(:record_type).permit(:name).merge(user_id: current_user.id)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:record_type_id, :qt, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  def show
    @user = User.find(params[:id])
  end

  protected

  # my custom fields are :name, :last_name
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :last_name,
        :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :last_name,
        :email, :password, :password_confirmation, :current_password)
    end
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  protected

    def after_sign_in_path_for(resource)
      user_path(resource)
    end

    def after_sign_up_path_for(resource)
      user_path(resource)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when 'success'
        'alert-success'
      when 'notice'
        'alert-info'
      when 'alert'
        'alert-danger'
      when :notice
        'alert-info'
      else
        flash_type.to_s
    end
  end

end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/record_types_helper.rb
module RecordTypesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/default/index.html.haml
%h1 Default#index
%p Find me in app/views/default/index.html.haml

app/views/layouts/_flash_messages.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Afighter
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  %body
    / Navigation
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Addiction fighter
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{:href => "#"} About
            - if user_signed_in?
              %li
                = link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Sign in', new_user_session_path
              %li
                = link_to 'Sign up', new_user_registration_path
        / /.navbar-collapse
      / /.container
    / Page Content
    .container#page-content
      .row
        .col-lg-12
          = render partial: 'layouts/flash_messages', flash: flash
          = yield

app/views/record_types/_form.html.haml
= form_for @record_type, class: 'form-horizontal' do |f|
  - if @record_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record_type.errors.count, "error")} prohibited this record_type from being saved:"
      %ul
        - @record_type.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'

app/views/record_types/edit.html.haml
%h1 Editing record_type

= render 'form'

= link_to 'Show', @record_type
\|
= link_to 'Back', record_types_path

app/views/record_types/index.html.haml
%h1 Listing record_types

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @record_types.each do |record_type|
      %tr
        %td= record_type.name
        %td= link_to 'Show', record_type
        %td= link_to 'Edit', edit_record_type_path(record_type)
        %td= link_to 'Destroy', record_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Record type', new_record_type_path

app/views/record_types/new.html.haml
%h1 New record_type

= render 'form'

= link_to 'Back', record_types_path

app/views/record_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @record_type.name

= link_to 'Edit', edit_record_type_path(@record_type)
\|
= link_to 'Back', record_types_path

app/views/records/_form.html.haml
= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      %ul
        - @record.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :record_type
    = f.text_field :record_type
  .field
    = f.label :qt
    = f.text_field :qt
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/records/edit.html.haml
%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
%h1 Listing records

%table
  %thead
    %tr
      %th Record type
      %th Qt
      %th User
      %th
      %th
      %th

  %tbody
    - @records.each do |record|
      %tr
        %td= record.record_type
        %td= record.qt
        %td= record.user
        %td= link_to 'Show', record
        %td= link_to 'Edit', edit_record_path(record)
        %td= link_to 'Destroy', record, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Record', new_record_path

app/views/records/new.html.haml
%h1 New record

= render 'form'

= link_to 'Back', records_path

app/views/records/show.html.haml
%p#notice= notice

%p
  %b Record type:
  = @record.record_type
%p
  %b Qt:
  = @record.qt
%p
  %b User:
  = @record.user

= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path